In [2]:
ord('a')

97

In [6]:
'camelCase'.isupper()

False

In [7]:
['a','b','c'].index('b')

1

In [15]:
import string

text.split()

['camelCaseCase']

In [24]:
text = None

def process(word):
    if word is None:
        return ''
    to_list = list(word)
    final_string = ''
    for idx, letter in enumerate(to_list):
        final_string += letter
        
        if len(to_list) == idx + 1:
            return final_string
        
        
        if to_list[idx + 1].isupper():
            final_string += ' '    

process(text)

    

''

In [25]:
len("***********")

11

'***********'

In [ ]:
ends = ['*' for _ in range(6 - 1)]
# full = ''.join(ends + ['*'] + ends)
full = ends + ['*'] + ends
test = full.copy()

test[0:4] = ' '
test[-3:-1] = ' '

[' ', '*', '*', '*', '*', ' ', '*']

In [57]:
def tower_builder(n_floors):
    ends = ['*' for _ in range(n_floors - 1)]
    full = ends + ['*'] + ends
    tower = []
    for idx in range(n_floors - 1, 0, -1):
        # print(full[idx, -idx])
        tower.append(''.join(full[idx:-idx]))
    
    return tower
        
print(tower_builder(6))

['*', '***', '*****', '*******', '*********']


In [79]:
s = "HelloWorld"
n = 3
replacement_char = '*'

# Replace first `n` characters
result = replacement_char * n + s[n:]
print(result)  

***loWorld


In [93]:
num = 3
full = ('*' * (num - 1)) + '*' + ('*' * (num - 1))
test = ' ' * 1
test + full[0:0] + test

'  '

In [96]:
def tower_builder(n_floors):
    full = ('*' * (n_floors - 1)) + '*' + ('*' * (n_floors - 1))
    tower = [full]
    for i in range(1, n_floors):
        blanks = ' ' * i
        tower.append(blanks + full[i:-i] + blanks)
    return sorted(tower)
    

tower_builder(3)

['  *  ', ' *** ', '*****']

In [ ]:
def tower_builder(n_floors):
    tower = []
    width = 2 * n_floors - 1
    for i in range(n_floors):
        stars = '*' * (2 * i + 1)
        tower.append(stars.center(width))
    return tower

tower_builder(3)

['  *  ', ' *** ', '*****']

In [1]:
len(" s p a c e s ")

13

In [4]:
text = " s p a c e s "
len(text.replace(' ', ''))

6

In [14]:
import string

waves = []
parsed = text.replace(' ', '')
for idx, letter in enumerate(text):
    if not letter.isalpha():
        continue
    
    waves.append(text[:idx] + text[idx].upper() + text[idx + 1:])
    
waves

[' S p a c e s ',
 ' s P a c e s ',
 ' s p A c e s ',
 ' s p a C e s ',
 ' s p a c E s ',
 ' s p a c e S ']

In [16]:
[text[:idx] + text[idx].upper() + text[idx + 1:] for idx, letter in enumerate(text) if letter.isalpha()]

[' S p a c e s ',
 ' s P a c e s ',
 ' s p A c e s ',
 ' s p a C e s ',
 ' s p a c E s ',
 ' s p a c e S ']

In [9]:
import string

string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [2]:
import math

5.6 % 1

0.5999999999999996

In [3]:
def round(num):
    return math.ceil(num) if num % 1 >= 0.5 else math.floor(num)

round(5.6)

6

In [4]:
round(4.3)

4

f"{value:{fill}{align}{width}}"

In [37]:
# def round(num):
#     return 0 if num < 0 else (255 if num > 255 else num)


def rgb(r, g, b):
    round = lambda num: min(255, max(num, 0))
    return '{:0>2X}{:0>2X}{:0>2X}'.format(round(r), round(g), round(b))


rgb(-20, 275, 125)

'00FF7D'

In [1]:
import numpy as np

def sum_pairs(ints, s):
    # return np.repeat(s, len(ints)) - np.array(ints)
    return np.array(ints)

sum_pairs([1, 4, 8, 7, 3, 15], 8)

array([ 1,  4,  8,  7,  3, 15])

In [ ]:
# reduction
test = np.array([1, 4, 8, 7, 3, 15])
s = np.repeat(8, len(test))
diff = s - test
mask = np.isin(diff, test)
indices = np.where(mask)[0]
indices


array([0, 1, 3])

In [26]:
diff

array([ 7,  4,  0,  1,  5, -7])

In [ ]:
reduced = test[indices]
pairs = None
min_index = 0
for idx, num in enumerate(reduced):
    if idx >= min_index and idx != 0:
        break
    res = np.where((diff[indices] == num) & (test[indices] != num))[0]
    # min_index = res[0] if res.size > 0 else min_index
        
    
print(min_index)
    

2


In [46]:
def sum_pairs(ints, s):
    ints_arr = np.array(ints)
    s_arr = np.repeat(s, len(ints))
    diff = s_arr - test
    mask = np.isin(diff, test)
    indices = np.where(mask)[0]
    min_index = 0
    pairs = None
    
    for idx, num in enumerate(ints_arr[indices]):
        if idx >= min_index and idx != 0:
            break
        
        res = np.where((diff[indices] == num) & (test[indices] != num))[0]
        if res.size > 0:
            test_val = res[0]
            min_index = min_index if test_val < min_index else test_val
            
    return min_index


l1 = [1, 4, 8, 7, 3, 15]
l2 = [1, -2, 3, 0, -6, 1]
l3 = [20, -13, 40]
l4 = [1, 2, 3, 4, 1, 0]
l5 = [10, 5, 2, 3, 7, 5]
l6 = [4, -2, 3, 3, 4]
l7 = [0, 2, 0]
l8 = [5, 9, 13, -3]
l9 = [1] * 10000000
l9[len(l9) // 2 - 1] = 6
l9[len(l9) // 2] = 7
l9[len(l9) - 2] = 8
l9[len(l9) - 1] = -3
l9[0] = 13
l9[1] = 3

sum_pairs(l4, 2)

0

In [41]:
reduced

array([1, 4, 7])

In [50]:
sum_array = np.full_like(l2, -6)

addend2 = sum_array - l2
addend2

array([-7, -4, -9, -6,  0, -7])

In [90]:
def sum_pairs(ints, s):
    sum_array = np.full_like(ints, s)
    ints_arr = np.array(ints)
    addend2 = sum_array - ints_arr
    mask = np.isin(addend2, ints_arr)
    indices = np.where(mask)[0]
    
    for idx in indices:
        print(ints_arr[idx], np.where(addend2 == ints_arr[idx]))
        
# sum_pairs(l4, 2)
sum_pairs(l4, 2)

1 (array([0, 4]),)
2 (array([5]),)
1 (array([0, 4]),)
0 (array([1]),)


In [1]:
from collections import Counter

In [6]:
test = [1, 1, 1, 2, 3]
for key, val in Counter(test).items():
    print(key, val)

1 3
2 1
3 1


In [7]:
divmod(5, 3)

(1, 2)